### PR TITLE
file class API PR

### PR DESCRIPTION
**Pull request by alex-mulkerrins**
File class API - pull request

### CODE REVIEW

**Comment by BozhidarVelikov** [comment]
Do you really need the variables for the std::string lineFromFile, charString and newFullPath. If you use them, use them only as local variables in the method that you need them. 

You don't use the variables row and col. 

Also, the vector content should keep the content of the file and when you read, you should actually read from there.

**Comment by TejasJD** [comment]
Hi Alex,
For the paths, maybe you could have a look at this [link](https://www.boost.org/doc/libs/1_80_0/libs/filesystem/doc/reference.html#class-path).

**Comment by alex-mulkerrins** [comment]
ok I will implement these updates and get rid of any unnecessary code. I'll also check out the link

**Comment by TejasJD** [comment]
> 
Yeah I agree with this.
Also, I think the the content can be implemented as a `std::map<int, std::string>` (ordered map or tree map in some languages) first field stores the line number. You can add, erase and replace specific lines and also iterate through efficiently.

**Comment by TejasJD** [comment]
I think we don't need the vector of content; we can always return a vector on demand when the person wants to read in the data from file into the program.

**Comment by alex-mulkerrins** [comment]
New updates to file management API:
We write to a file from a content vector
We load from file into a content vector
We can manipulate the data from the content vector
create a new file using saveAs
and delete a specified file

We can also make a directory
and delete a directory

**Comment by alex-mulkerrins** [comment]
Fixed bugs and provided update to file class

Will close for now.

**Comment by TejasJD** [comment]
Yeah, this seems fine, ready for merge.

**Pull request merged**
